[[plugins]]
package = "netlify-plugin-subfont"
    [plugins.inputs]
    # Inline generated CSS @font-face blocks into each page
    # When set to `false` an external CSS file will be created
    inlineCss = true

    # Inline generated font subsets into their respective @font-face blocks
    # When set to `false` external font files will be created
    inlineFonts = true
