[[headers]]
    for = "/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        X-Content-Type-Options = "nosniff"
[[headers]]
    for = "/"
    [headers.values]
        Cache-Control = "public, no-cache"
[[headers]]
    for = "/manifest.webmanifest"
    [headers.values]
        Content-Type = "application/manifest+json; charset=utf-8"
