[[headers]]
    for = "/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"
        X-Content-Type-Options = "nosniff"
[[headers]]
    for = "/"
    [headers.values]
        Cache-Control = "public, no-cache"
[[headers]]
    for = "/manifest.webmanifest"
    [headers.values]
        Content-Type = "application/manifest+json; charset=utf-8"

[[plugins]]
package = "netlify-plugin-subfont"
    [plugins.inputs]
    # Inline generated CSS @font-face blocks into each page
    # When set to `false` an external CSS file will be created
    inlineCss = true

    # Inline generated font subsets into their respective @font-face blocks
    # When set to `false` external font files will be created
    inlineFonts = true
